<?php
// Renvoie tab avec la recherche en prenant un token et string 
function SearchTrack($token,$name_search,$limit=10)
{
    //Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $name_search = str_replace(' ', '%20', $name_search);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.spotify.com/v1/search?q='.$name_search.'&type=track&market=FR&limit='.$limit);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer ' . $token;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $jsonObj2 = json_decode($result);

    $tab = array(array());
    for($i=0;$i<$limit;$i++){
        $tab[$i][0] = $jsonObj2->tracks->items[$i]->name ;  // Name
        $tab[$i][1] = $jsonObj2->tracks->items[$i]->album->artists[0]->id; //Song ID
        $tab[$i][2] = $jsonObj2->tracks->items[$i]->preview_url; // Song preview
        $tab[$i][3] = $jsonObj2->tracks->items[$i]->popularity; // Song popularity
        $tab[$i][4] = $jsonObj2->tracks->items[$i]->album->images[0]->url; // Song url
        $tab[$i][5] = $jsonObj2->tracks->items[$i]->album->release_date; // Song date
        $tab[$i][6] = $jsonObj2->tracks->items[$i]->album->artists[0]->name; // tab Nam
        $tab[$i][7] = $jsonObj2->tracks->items[$i]->album->artists[0]->id; // tab ID
        $tab[$i][8] = $jsonObj2->tracks->items[$i]->uri ;  // URI
        $tab[$i][9] = $jsonObj2->tracks->items[$i]->album->images[0]->url; // Song url
        //$tab[$i][10] = $jsonObj2->tracks->items[$i]->ablum->name; //Album Name
        }



     
 // echo $result;
    return $tab;
}
?>

<?php


function Token()
{
    $date = date('d-m-y h:i:s');
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://accounts.spotify.com/api/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=refresh_token&refresh_token=AQD8YFwmBeHALzNEW0jN6DcyJqVjYh2Ys_a1cN9Wtm2AdcAeLsf_hWpfmuWVF956-aooxETLQq6J--RdqWmowKDE0FOt-e2ruP4DZSYad5SkhHGn0xIm_vYIaZg0aobg7Pk");

    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    $headers[] = 'Authorization: Basic MWM2MTAyNTRmZWRjNGJhZWJjY2M1ODU4YjI2MmI2M2Q6Y2NiOTBkNTZmYzY3NGM5OTlkODNkYmU2NjBjNDcyZmM=';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    #echo($result);
    $jsonObj = json_decode($result);
    //  echo ("Token : --> ");
    //echo $jsonObj->access_token ."\n";
    $TOKEN_ID = $jsonObj->access_token;

    return [$TOKEN_ID,$jsonObj->expires_in,$date];
}

function Requete($token){
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.spotify.com/v1/me');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer ' . $token;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
  //echo $result;
  return $result;
}

$stop = 0;
function TestToken($token){
  echo "\033[34m\n\n TEST DU TOKEN....    \n\n\033[0m";
  
  if ( strlen($token) != 286 || substr(Requete($token), 0, 11)== "{\n  \"error\""){
      echo "\033[31m ! Token non conforme !\033[0m\n\n";
      echo " Generation Nouveau Token ...\n";
  
      echo "Nouveau Token Généré !\n";
      $token = Token()[0];
      TestToken($token);
 }
 else if (substr(Requete($token), 0, 13)=="{\n  \"country\""){
    echo "\033[32m |--------------| \n";
    echo " | Token Valide | \n";
    echo " |--------------|\n\033[0m";
    //echo "Token en cours : \n";
    //echo $token."\n";
    return $token;
 }
 else {
  echo "\033[31m Erreur du token inconnu \033[0m\n\n";

 }

}
$token = Token();
?>

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <title>Music Project</title>
    </head>
    <body>
        <table>
        <?php
            $token = $token[0];
            //echo'<tr> <th>Nom</th> <th>Album</th> <th>Pochette</th> <th></th> </tr>';
            $tab = SearchTrack($token,$_GET['Musique']);
            for($i=0;$i<10;$i++)
            {
            //echo '<tr>  <td>'.$tab[$i][6].'</td> <td>'.$tab[$i][0].'</td> <td>'.'<img src="'.$tab[$i][9].'" alt="test">'.'</td><td><form method="GET" action="merci"><input type="hidden" name="uri" value="'.$tab[$i][8].'"><input type="image" src="https://pbs.twimg.com/media/FmvNLj4X0AEqgaS?format=jpg&name=900x900"></form></td></tr>';
            echo '<tr class="Colonne">  <td class="Image">'.'<img src="'.$tab[$i][9].'" alt="test">'.'</td> <td class="Nom">'.$tab[$i][0].'<br> <h1>'.$tab[$i][6].'</h1></td><td class="Nom"><form method="GET" action="merci"><input type="hidden" name="uri" value="'.$tab[$i][8].'"><input type="image" src="https://pbs.twimg.com/media/FmvNLj4X0AEqgaS?format=jpg&name=900x900"></form></td></tr>';

            }
        ?>
        </table>
    </body>
    <style>
        
        *{  
            border-radius: 360px;
            background-color:#4D4A45;
            color: #FAA105;
            font-family: sans-serif;
        }
        th, td {
            border: 0px solid #FAA105;
            border-radius: 30px; 
            max-width: 100px;           
        }

        th{
        padding-top:10px;
        border-radius: 30px;
        padding-bottom:10px;
        }
        
        table {
            border-collapse: collapse;
            border: 0px;
            margin: auto;
            width:75%;
            text-align: center;
            font-size:2.5em;
        }

        img{
            
            max-width: 20%;
        }

        input{
         border: 5px solid #FAA105;
         max-width: 10%;
         border-radius: 10000px;
         color: #FAA105;
        }

        .Nom{
            text-align: left;
        }
        .Image{
            text-align: right;
            padding-right: 10px;
        }
        .Colonne{
            margin-bottom: 10px;
        }
        h1{
            font-size: 0.8em;
            font-weight: normal;
            color: #FAA105;
            margin-top: -5px;
        }
        
    </style>
</html>